### ISSUE TITLE
Pygls 0.9.0 broke this program

### ISSUE THREAD

**Issue by otreblan** [regen100/cmake-language-server#10]
In the `setup.py` pygls is required as <0.9.0.

**Comment by regen100** [comment]
`setup.py` already requires `pygls>=0.8.1,<0.9.0`.

Here is the part of [`setup.py`](https://files.pythonhosted.org/packages/68/07/8516df005ea953e28e20ac285535784fc3bcfb2cf0f26e354025fc4fa853/cmake-language-server-0.1.1.tar.gz):
```
install_requires = \
['pygls>=0.8.1,<0.9.0', 'pyparsing>=2.4,<3.0']
```

However, it should cope with Pygls 0.9.0. I will update the code in another PR.
