### ISSUE TITLE
The `textDocument/completion` request may not contains the `request` parameter

### ISSUE THREAD

**Issue by CharlesGueunet** [regen100/cmake-language-server#11]
Hello,

Thank you for this server,

I have a problem using this LSP server, concerning the `textDocument/completion` request. It seems the server expect a `context` parameter while the LSP specification if I am not mistaken has it as optional:
From the [microsoft website](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion)
```
Request:

method: ‘textDocument/completion’

params: CompletionParams defined as follows:

export interface CompletionParams extends TextDocumentPositionParams, WorkDoneProgressParams, PartialResultParams {
	/**
	 * The completion context. This is only available if the client specifies
	 * to send this using `ClientCapabilities.textDocument.completion.contextSupport === true`
	 */
	context?: CompletionContext;
}
```

For context, I am trying to make this LSP server works with the kakoune lsp plugin [see related issue here](https://github.com/ul/kak-lsp/issues/311).

**Comment by CharlesGueunet** [comment]
Thanks for the quickfix, using it I have an error as `self._api` is None ten lines below. Do you have an idea if I missed a configuration or if this is a bug ? (I can open an issue if you prefer)

**Comment by regen100** [comment]
It looks like another bug. Please open the new issue.
