### ISSUE TITLE
Missing target_precompile_headers

### ISSUE THREAD

**Issue by sum01** [regen100/cmake-language-server#14]
[target_precompile_headers](https://cmake.org/cmake/help/latest/command/target_precompile_headers.html)

---

As a side note, do you have any desire to support included packages (that are distributed) that bring in their own vars/functions? Things like `FindPackageHandleStandardArgs`, `FindPackageMessage`, or `cmake_dependent_option` as an example.

**Comment by regen100** [comment]
In my environment (CMake  3.17.2, NVIM v0.4.3, coc.nvim), `target_precompile_headers` is listed in the completion list. Please check the version.

![screenshot](https://user-images.githubusercontent.com/4144526/82114028-254dd300-9795-11ea-9938-4a611d9eadab.png)

And I created #15 for supporting `FindPackageHandleStandardArgs` etc.

**Comment by sum01** [comment]
Seems fine after an update, sorry. Ignore me
