### ISSUE TITLE
insertText property provided with null

### ISSUE THREAD

**Issue by Shatur95** [regen100/cmake-language-server#16]
Several LSP plugins, such as nvim-native, vim-lamp (already fixed in https://github.com/hrsh7th/vim-lamp/issues/21) and vim-lsp have no completion with it.
Author of vim-lamp [said](https://github.com/hrsh7th/vim-lamp/issues/21#issuecomment-628455296) that `cmake-language-server` provided `insertText` with `null`.
Could you fix it?

**Comment by regen100** [comment]
I made the commit https://github.com/regen100/cmake-language-server/commit/3c171b9e25d3de75129f37716601bcf7b1efea3a to add `insertText` but this commit is in only master branch and not released. I will release a new version.
Thank you for reporting!

**Comment by Shatur95** [comment]
You are right, the latest master works as expected, sorry!
