### ISSUE TITLE
Thoughts on the formatter

### ISSUE THREAD

**Issue by sum01** [regen100/cmake-language-server#25]
I just noticed that there doesn't seem to be much/any documentation on the formatter's options/args, and was wondering if it's configurable, and/or what the defaults even are?

As an aside, do you have any thoughts on splitting the formatter into its own package? I'm just saying this because I noticed that this LSP actually conflicts (same binary name `cmake-format`) with https://github.com/cheshirekow/cmake_format which seems to possibly be a more fleshed out formatter.

**Comment by regen100** [comment]
I'm planning to replace the formatter by cheshirekow/cmake_format or other external ones.

**Comment by thetic** [comment]
Can we have an option to disable to formatter until these improvements land?

**Comment by regen100** [comment]
In the new version `0.1.4`, the installation of `cmake-format` command was deleted to resolve the conflict (#50).
