### ISSUE TITLE
Vim ALE LSP server configuration

### ISSUE THREAD

**Issue by Rubonnek** [regen100/cmake-language-server#33]
Has anyone tested this with [Vim ALE](https://github.com/dense-analysis/ale)?

I'm not sure how to set it up yet.

**Comment by Rubonnek** [comment]
Well, it would be something similar to this (but it's obviously non-working):

```
call ale#linter#Define('cmake', {
\   'name': 'cmake-language-server',
\   'lsp': 'stdio',
\   'executable': 'cmake-language-server',
\   'command': '%e',
\   'project_root': function('ale_linters#c#cquery#GetProjectRoot'),
\   'initialization_options': function('ale_linters#c#cquery#GetInitializationOptions'),
\})
```

There's an example for registering cmakelint which is now deprecated (and not exactly an LSP server):
https://github.com/dense-analysis/ale/blob/master/ale_linters/cmake/cmakelint.vim

**Comment by KoviRobi** [comment]
I have the following in my localvimrc:
```
function! Cmakels_project_root(buffer)
  let l:builddir = ale#path#FindNearestDirectory(a:buffer, "build/")
  return fnamemodify(l:builddir, ":p:h")
endfunction

call ale#linter#Define('cmake', {
\   'name': 'cmake-language-server',
\   'lsp': 'stdio',
\   'executable': 'cmake-language-server',
\   'command': '%e',
\   'project_root': function('Cmakels_project_root'),
\})
let g:ale_linters.cmake = [ "cmake-language-server" ]
```
First it finds upwards for a `build` directory, then it uses the parent directory of the `build` directory. Seems to work okay, though it only offers documentation for built-ins, it doesn't pick up documentation comments for custom functions which have `## @brief` comments.

**Comment by Rubonnek** [comment]
@KoviRobi thank you!
