### ISSUE TITLE
cmake-format from standard input

### ISSUE THREAD

**Issue by lassik** [regen100/cmake-language-server#4]
Can `cmake-format` have support for formatting a file from standard input to standard output? Something like `cmake-format --stdin`. This would be useful for editor plugins.

**Comment by lassik** [comment]
Another way is to format from stdin when no filenames are given on the command line. `gofmt` does that, for example.

**Comment by regen100** [comment]
OK, I'll add stdin mode and release a new version over the weekend.

**Comment by lassik** [comment]
Thank you very much.
