### ISSUE TITLE
How to specify configuration options for cmake-format?

### ISSUE THREAD

**Issue by miguno** [regen100/cmake-language-server#65]
See title. I'd like to pass configuration settings to cmake-format, such as `--enable-markup false`. I didn't spot anything in the docs and code that seems to allow such customization.

**Comment by syyyr** [comment]
It seems that cmake-format arguments are hardcoded: https://github.com/regen100/cmake-language-server/blob/master/cmake_language_server/server.py#L165

I guess your only option is to use a configuration file as described here: https://cmake-format.readthedocs.io/en/latest/configuration.html

**Comment by miguno** [comment]
Ok. Thank you!
