### ISSUE TITLE
Errors/Warnings are not displayed, difficulty configuring

### ISSUE THREAD

**Issue by kioplato** [regen100/cmake-language-server#75]
Hello. I'm having difficulty configuring the language server. I'm using neovim and the server attaches correctly. However, no errors or warnings are being displayed. Probably it's because I failed to configure the CMake API as described [here](https://github.com/regen100/cmake-language-server#configuration).

How can I create the necessary files for the CMake API? I'm using Ubuntu 22.04 and found [the related CMake docs](https://cmake.org/cmake/help/latest/manual/cmake-file-api.7.html?highlight=api#cmake-file-api-7) but they don't have any information on generating the related files. I'm assuming I need to generate a file similar to compile-commands.json?

**Comment by Freed-Wu** [comment]
> I'm assuming I need to generate a file similar to compile-commands.json?

No, It can work without any compile-commands.json.

**Comment by vRoussel** [comment]
@kioplato I have the same issue, did you end up finding a solution?

**Comment by regen100** [comment]
This LSP does not currently support diagnostics. As Freed-Wu mentioned, you can try using neocmakelsp.
