### ISSUE TITLE
Support python 3.12

### ISSUE THREAD

**Issue by kbrowder** [regen100/cmake-language-server#82]
Python 3.12 has been released, my guess is this probably just needs updates to tox.ini and pyproject.toml

**Comment by tannal** [comment]
+1

**Comment by tan-wei** [comment]
+1

**Comment by BharatNanwani** [comment]
I have python3.12 installed. I installed python3.11 also. but cmake doesn't start until I point python3 to python3.11. but otherwise there are other programs in my system that need python3.12. I am not very fimiliar how python works. ANy suggestions?

**Comment by tan-wei** [comment]
@BharatNanwani Waiting for #85 is finished and merged.

**Comment by tan-wei** [comment]
Should be closed due to 0.1.9 is released.
